// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.policies.applied", true);
user_pref("browser.region.update.updated", 1750419368);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1750419367);
user_pref("calendar.list.sortOrder", "9c1d0b32-3421-4c4d-96cc-8cc352c04ae6");
user_pref("calendar.registry.9c1d0b32-3421-4c4d-96cc-8cc352c04ae6.calendar-main-default", true);
user_pref("calendar.registry.9c1d0b32-3421-4c4d-96cc-8cc352c04ae6.calendar-main-in-composite", true);
user_pref("calendar.registry.9c1d0b32-3421-4c4d-96cc-8cc352c04ae6.disabled", true);
user_pref("calendar.registry.9c1d0b32-3421-4c4d-96cc-8cc352c04ae6.name", "Home");
user_pref("calendar.registry.9c1d0b32-3421-4c4d-96cc-8cc352c04ae6.type", "storage");
user_pref("calendar.registry.9c1d0b32-3421-4c4d-96cc-8cc352c04ae6.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1750419376841");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1750419385);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.installedDistroAddon.langpack-en-CA@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-GB@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-US@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20250606210711");
user_pref("extensions.lastAppVersion", "128.11.1");
user_pref("extensions.lastPlatformVersion", "128.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"b6766cc8-578f-4980-ac20-a958cae27261\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "622d9020-b349-42a3-8e76-80a266715fd");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.11.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1750419384);
user_pref("toolkit.telemetry.cachedClientID", "5c53a58a-2edb-4747-9cd9-d657516f44a9");
user_pref("toolkit.telemetry.previousBuildID", "20250606210711");
